  server:
    port: 8081
    error:
      include-message: always
      include-binding-errors: always

  spring:
    datasource:
      password: root
      url: jdbc:postgresql://localhost:5432/migrationappp
      username: postgres
    jpa:
      hibernate:
        ddl-auto:   update #create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

    mail:
      host: smtp.office365.com
      port: 587
      username: rayen.hedfi99@gmail.com
      password: 181jmT0628//

      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
  bezkoder:
    app:
     jwtSecret: bezKoderSecretKey
     jwtExpirationMs: 86400000

